// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DefaultSuiteTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void 1Addnewtasks() {
    driver.Navigate().GoToUrl("https://todomvc.com/examples/vanillajs/");
    driver.FindElement(By.CssSelector(".new-todo")).Click();
    driver.FindElement(By.CssSelector(".new-todo")).SendKeys("toast bread");
    driver.FindElement(By.CssSelector(".new-todo")).SendKeys(Keys.Enter);
    driver.FindElement(By.CssSelector(".new-todo")).SendKeys("prepare ingredients");
    driver.FindElement(By.CssSelector(".new-todo")).SendKeys(Keys.Enter);
    driver.FindElement(By.CssSelector(".new-todo")).SendKeys("assemble sandwhich");
    driver.FindElement(By.CssSelector(".new-todo")).SendKeys(Keys.Enter);
    driver.FindElement(By.CssSelector(".new-todo")).SendKeys("cut and serve");
    driver.FindElement(By.CssSelector(".new-todo")).SendKeys(Keys.Enter);
  }
  [Test]
  public void 2Edittask() {
    driver.Navigate().GoToUrl("https://todomvc.com/examples/vanillajs/");
    driver.FindElement(By.CssSelector("li:nth-child(1) label")).Click();
    driver.FindElement(By.CssSelector("li:nth-child(1) label")).Click();
    {
      var element = driver.FindElement(By.CssSelector("li:nth-child(1) label"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.CssSelector(".edit")).Click();
    driver.FindElement(By.CssSelector(".edit")).SendKeys("Toast bread");
    driver.FindElement(By.CssSelector("li:nth-child(2) label")).Click();
    driver.FindElement(By.CssSelector("li:nth-child(2) label")).Click();
    {
      var element = driver.FindElement(By.CssSelector("li:nth-child(2) label"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.CssSelector(".edit")).Click();
    driver.FindElement(By.CssSelector(".edit")).SendKeys("prepare Ingredients");
    driver.FindElement(By.CssSelector("li:nth-child(3) label")).Click();
    driver.FindElement(By.CssSelector("li:nth-child(3) label")).Click();
    {
      var element = driver.FindElement(By.CssSelector("li:nth-child(3) label"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.CssSelector(".edit")).Click();
    driver.FindElement(By.CssSelector(".edit")).SendKeys("Assemble sandwhich");
    driver.FindElement(By.CssSelector("li:nth-child(4) label")).Click();
    driver.FindElement(By.CssSelector("li:nth-child(4) label")).Click();
    {
      var element = driver.FindElement(By.CssSelector("li:nth-child(4) label"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.CssSelector(".edit")).Click();
    driver.FindElement(By.CssSelector(".edit")).SendKeys("Cut and serve");
    driver.FindElement(By.CssSelector("li:nth-child(3) label")).Click();
  }
  [Test]
  public void 3Markataskascomplete() {
    driver.Navigate().GoToUrl("https://todomvc.com/examples/vanillajs/");
    driver.Manage().Window.Size = new System.Drawing.Size(500, 413);
    driver.FindElement(By.CssSelector("li:nth-child(1) .toggle")).Click();
    driver.FindElement(By.LinkText("Completed")).Click();
  }
  [Test]
  public void 4Filtertaskbystatus() {
    driver.Navigate().GoToUrl("https://todomvc.com/examples/vanillajs/");
    driver.FindElement(By.LinkText("Active")).Click();
    driver.FindElement(By.LinkText("Completed")).Click();
    driver.FindElement(By.LinkText("All")).Click();
    driver.FindElement(By.CssSelector("html")).Click();
  }
  [Test]
  public void 5Deleteatask() {
    driver.Navigate().GoToUrl("https://todomvc.com/examples/vanillajs/");
    driver.Manage().Window.Size = new System.Drawing.Size(750, 675);
    driver.FindElement(By.CssSelector("li:nth-child(4) .toggle")).Click();
    driver.FindElement(By.CssSelector(".completed:nth-child(4) .destroy")).Click();
  }
  [Test]
  public void 6Markalltasksascomplete() {
    driver.Navigate().GoToUrl("https://todomvc.com/examples/vanillajs/");
    driver.FindElement(By.CssSelector("li:nth-child(2) .toggle")).Click();
    driver.FindElement(By.CssSelector("li:nth-child(3) .toggle")).Click();
  }
  [Test]
  public void 7Clearcompletedtasks() {
    driver.Navigate().GoToUrl("https://todomvc.com/examples/vanillajs/");
    driver.FindElement(By.CssSelector(".clear-completed")).Click();
  }
  [Test]
  public void 8Persistence() {
    driver.Navigate().GoToUrl("https://todomvc.com/examples/vanillajs/");
    driver.FindElement(By.CssSelector(".new-todo")).SendKeys("eat the sandwhich");
    driver.FindElement(By.CssSelector(".new-todo")).SendKeys(Keys.Enter);
  }
  [Test]
  public void 9Keyboardshortcuts() {
    driver.Navigate().GoToUrl("https://todomvc.com/examples/vanillajs/");
    driver.Manage().Window.Size = new System.Drawing.Size(500, 413);
    driver.FindElement(By.CssSelector(".new-todo")).Click();
    driver.FindElement(By.CssSelector(".new-todo")).SendKeys("cooking tonight");
    driver.FindElement(By.CssSelector(".new-todo")).SendKeys(Keys.Enter);
    driver.FindElement(By.CssSelector(".view > label")).Click();
    driver.FindElement(By.CssSelector(".view > label")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".view > label"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.CssSelector(".edit")).Click();
    driver.FindElement(By.CssSelector(".edit")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".edit"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.CssSelector(".edit")).SendKeys("takeaway tonight");
  }
}
